FROM node:22 as base
WORKDIR /app
RUN npm i -g pnpm
COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

FROM node:22-alpine3.19 as release
WORKDIR /app
RUN npm i -g pnpm

COPY --from=base /app/package.json ./package.json
COPY --from=base /app/src ./src
COPY --from=base /app .

EXPOSE 3000

CMD ["pnpm", "dev"]
